#include "preprocess.h"
#include <cmath>
#include <algorithm>

// Center crop: take a CROP_SIZE×CROP_SIZE square from the middle of the frame.
// FRAME_H (240) is the limiting dimension; x offset centres horizontally.
static constexpr int CROP_SIZE = FRAME_H;                      // 240
static constexpr int CROP_X    = (FRAME_W - CROP_SIZE) / 2;   // 40
static constexpr int CROP_Y    = 0;

// Quantise a [0,255] uint8 channel value to int8 using model quantisation params.
static inline int8_t quantize(uint8_t val)
{
    // int8 = clamp(round(float_val / scale) + zero_point, -128, 127)
    // INPUT_SCALE and INPUT_ZERO_POINT are defined in model.h (generated by convert_and_export.py).
    float q = roundf((float)val / INPUT_SCALE) + (float)INPUT_ZERO_POINT;
    if (q > 127.0f)  return  127;
    if (q < -128.0f) return -128;
    return (int8_t)q;
}

void preprocess_frame(const uint8_t *rgb565_frame, int8_t *output_int8)
{
    for (int out_y = 0; out_y < TARGET_SIZE; out_y++) {
        for (int out_x = 0; out_x < TARGET_SIZE; out_x++) {
            // Map output pixel back to source (nearest-neighbour)
            int src_x = CROP_X + (out_x * CROP_SIZE) / TARGET_SIZE;
            int src_y = CROP_Y + (out_y * CROP_SIZE) / TARGET_SIZE;

            // RGB565 is stored big-endian by esp32-camera (high byte first)
            int src_idx = (src_y * FRAME_W + src_x) * 2;
            uint16_t pixel = ((uint16_t)rgb565_frame[src_idx] << 8)
                           |  (uint16_t)rgb565_frame[src_idx + 1];

            // Unpack RGB565 → RGB888 (simple bit-shift expansion)
            uint8_t r = ((pixel >> 11) & 0x1F) << 3;
            uint8_t g = ((pixel >>  5) & 0x3F) << 2;
            uint8_t b =  (pixel        & 0x1F) << 3;

            int out_idx = (out_y * TARGET_SIZE + out_x) * 3;
            output_int8[out_idx + 0] = quantize(r);
            output_int8[out_idx + 1] = quantize(g);
            output_int8[out_idx + 2] = quantize(b);
        }
    }
}
